/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   open_window.c                                      :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: uxmancis <uxmancis>                        +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/09/04 17:14:32 by jllarena          #+#    #+#             */
/*   Updated: 2024/09/21 18:23:37 by uxmancis         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../includes/cub3d.h"

/* close_handler: ESC or x (window) are pressed
*   from: Uxu's fractol
*/
int	close_handler(t_mlx *mlx)
{
	mlx_destroy_image(mlx->mlx_connection, mlx->mlx_ptr);
	mlx_destroy_window(mlx->mlx_connection, mlx->win_ptr);
	free(mlx->mlx_connection);
	exit(EXIT_SUCCESS);
}

/* Updates player position info stored in cub. Both mlx-s get data from 
*   cub. This means by updated cub directly, the info both mlx are getting
*    is updated.
*
*   When moving forward: (pixel language) x stays the same, y is decreased. Because (0,0) in pixels 
* starts up on the left and increases by going right/down on the window (pixel language)*/
void move_forward(t_data *data)
{
    printf(MAGENTA"------------------------------move_forward------------------------------\n"RESET_COLOUR);
    printf("            |  x_decimal|  x_pixel  |  y_decimal  |  y_pixel  |\n");
    printf("> Before    |  %.2f     |     %d    |     %.2f    |     %d    |\n", data->cub->player_position->x_decimal, data->cub->player_position->x_pixel, data->cub->player_position->y_decimal, data->cub->player_position->y_pixel);
    // printf("Before: x (decimal) = %2.f, y (decimal) = %2.f\n", cub->player_position.x_decimal, cub->player_position.y_decimal);
    // printf("Before: x (pixel) = %d, y (pixel) = %d\n", cub->player_position.x_pixel, cub->player_position.y_pixel);
    data->cub->player_position->y_pixel -= 1; //Decreases 1 pixel (minimum movement option in 2d map window);
    data->cub->player_position->y_decimal = pixel_to_decimal(data->cub->player_position->y_pixel, Y_HEIGHT);
    my_mlx_pixel_put(data->mlx_map, data->cub->player_position->x_pixel, data->cub->player_position->y_pixel, 0x00FF0000);

    // printf("After: x (decimal) = %2.f, y (decimal) = %2.f\n", cub->player_position.x_decimal, cub->player_position.y_decimal);
    // printf("Before: x (pixel) = %d, y (pixel) = %d\n", cub->player_position.x_pixel, cub->player_position.y_pixel);
    printf("> After     |  %.2f     |     %d    |     %.2f    |     %d    |\n", data->cub->player_position->x_decimal, data->cub->player_position->x_pixel, data->cub->player_position->y_decimal, data->cub->player_position->y_pixel);
}

// void move_backward(t_data *data)
// {
    
// }

/* key_handler:
*		Input: keycode generated by mlx_mouse_hook.
*		
*		Works as an index for keyboard-related events.
*		Depending on the keycode (event identifier) received, 
*		key_handler will decide how the program should act
*		by calling to a function or to another.
*	
*		Managed events: 
*			53 : ESC
*			123 : Key Right
*			124 : Key Left
*			125 : Key Down
*			126 : Key Up
*/
// int	key_handler(int keycode, t_mlx *mlx)
int key_handler(int keycode, t_data *data)
{
	printf("inside key_handler, keycode = %d\n", keycode);
    // if (keycode == ESC || keycode == CLOSE)
	// {
	// 	close_handler(mlx);
	// 	return (0);
	// }
	if (keycode == W_MOVE_FORWARD)
    {
        printf("W key pressed - Move FORWARD\n");
        move_forward(data); //lo que yo creo: cualquiera
    }
        
	if (keycode == S_MOVE_BACKWARDS)
        printf("S key pressed - Move BACKWARDS\n");
	if (keycode == A_MOVE_LEFT)
        printf("S key pressed - Move LEFT\n");
	if (keycode == D_MOVE_RIGHT)
        printf("D key pressed - Move RIGHT\n");
    if (keycode == ROTATE_LEFT)
        printf("Left arrow key pressed - Rotate LEFT\n");
    if (keycode == ROTATE_RIGHT)
    {
        printf("Left arrow key pressed - Rotate RIGHT\n");
    }
	//ft_render(mlx); //FP: Future Problem
	// printf(GREEN"After each KEY_HANDLER call:--------------------------------\n"RESET_COLOUR);
    // printf("            | mlx_game   |  mlx_map  |\n");
    // printf("x_index     |    %d       |    %d      |\n", data->mlx_game->cub->player_position->x_index, data->mlx_map->cub->player_position->x_index);
    // printf("x_decimal   |    %.2f    |    %.2f   |\n", data->mlx_game->cub->player_position->x_decimal, data->mlx_map->cub->player_position->x_decimal);
    // printf("x_pixel     |    %d      |    %d     |\n", data->mlx_game->cub->player_position->x_pixel, data->mlx_map->cub->player_position->x_pixel);
    // printf("y_index     |    %d      |    %d     |\n", data->mlx_game->cub->player_position->y_index, data->mlx_map->cub->player_position->y_index);
    // printf("y_decimal   |   %.2f    |   %.2f   |\n", data->mlx_game->cub->player_position->y_decimal, data->mlx_map->cub->player_position->y_decimal);
    // printf("y_pixel     |    %d      |    %d     |\n", data->mlx_game->cub->player_position->x_pixel, data->mlx_map->cub->player_position->x_pixel);
    return (0);
}

//Javi's
int close_program(t_mlx *mlx)
{
    if (mlx && mlx->win_ptr)
        mlx_destroy_window(mlx->mlx_ptr, mlx->win_ptr);
    exit(EXIT_SUCCESS);
    return (0);
}

//Javi's
int handle_keypress(int keycode, t_mlx *mlx)
{
    if (keycode == 65307) // ESC boton 
        close_program(mlx);
    return (0);
}

// void ft_events_init(t_mlx *mlx)
void ft_events_init(t_data *data)
{
    /* 'x' closing button: evento 17 */
    mlx_hook(data->mlx_game->win_ptr, 17, 0, (int (*)(void *))close_program, data->mlx_game);//línea Javi
    mlx_hook(data->mlx_map->win_ptr, 17, 0, (int (*)(void *))close_program, data->mlx_map);//línea Javi
    //mlx_hook(mlx->win_ptr, 17, (1L << 17), &close_program, mlx); //también funciona, opción Uxue

    /* ESC */
    // Añadir un hook para cerrar con la tecla ESC (evento 2 para keypress)
    //usar 1L<<0 activa específicamente la máscara para el evento de KeyPress.
    mlx_hook(data->mlx_game->win_ptr, 2,  1L<<0, handle_keypress, data->mlx_game);
    mlx_hook(data->mlx_map->win_ptr, 2,  1L<<0, handle_keypress, data->mlx_map);

    /*Defines which is the function that is going to take care of keys: key_handler
    * When key is pressed, it will be sent to key_handler.
    *   Aim: with 2 lines, both windows can get key presses and cub will be updated for both
    *------------------------------------------------------------------------------*/
    mlx_key_hook(data->mlx_game->win_ptr, &key_handler, data);
    mlx_key_hook(data->mlx_map->win_ptr, &key_handler, data);
}

/*  Initializes window with different size (height & width) depending
*   on wether if window is for Cub3D game window (mlx_game) or
*   for maze map window (mlx_map).
*/
void my_mlx_new_window(t_mlx *mlx, enum window_type game_or_map)
{
    //printf(GREEN"my_mlx_new_window\n");
    mlx->win_ptr = NULL;
    if (game_or_map == GAME)
        mlx->win_ptr = mlx_new_window(mlx->mlx_ptr, HEIGHT_WINDOW, WIDTH_WINDOW, "Cub3D");
    else if (game_or_map == MAP)
        mlx->win_ptr = mlx_new_window(mlx->mlx_ptr, HEIGHT_MAP, WIDTH_MAP, "Map - Debugging purposes");
    if (!mlx->win_ptr)
        exit_with_error("Failed to create window\n");
}

/*  Initializes image with different size (height & width) depending
*   on wether if image is for Cub3D game window (mlx_game) or
*   for maze map window (mlx_map).
*/
void my_mlx_new_image(t_mlx *mlx, enum window_type game_or_map)
{
    //printf("image_ptr = %p\n", mlx->image_ptr);
    mlx->image_ptr = NULL;
    if (game_or_map == GAME)
        mlx->image_ptr = mlx_new_image(mlx->mlx_ptr, HEIGHT_WINDOW, WIDTH_WINDOW);
    else if (game_or_map == MAP)
        mlx->image_ptr = mlx_new_image(mlx->mlx_ptr, HEIGHT_MAP, WIDTH_MAP);
    if (!mlx->image_ptr)
        exit_with_error("Failed to create image\n");
    else
        printf("IMAGE_PTR successfully created = %p\n", mlx->image_ptr);
    //printf(MAGENTA"my_mlx_new_image\n");
}

void init_window(t_mlx *mlx, enum window_type game_or_map, t_cub *cub)
{
    mlx->mlx_ptr = mlx_init();
    if (!mlx->mlx_ptr)
    {
        exit_with_error("Failed to initialize mlx");
        free (mlx->mlx_ptr);
        free (mlx);
    }

    /* Create New Window: mlx_new_window*/
    my_mlx_new_window(mlx, game_or_map);
    my_mlx_new_image(mlx, game_or_map);

    /* Get Address: whatever mlx_game of mlx_map, works for both */
    mlx->pixels_ptr = mlx_get_data_addr(mlx->image_ptr, &mlx->bpp, &mlx->line_len, &mlx->endian);
    printf(YELLOW"mlx->pixels_ptr = %p\n"RESET_COLOUR, mlx->pixels_ptr);

    /* Tenemos 1 instancia de cub. Hacemos que ambas ventanas (mlx) apunten a esta misma única instancia de cub*/
    mlx->cub = cub;
    
    /* Initialize events: key presses*/
    // ft_events_init(mlx);

    if (game_or_map == MAP)
    {
        put_walls_in_map(mlx);
    }
    //mlx->cub = &cub;
}

/*   Keeps application running, continuously listening for events
*    like key presses, mouse movements, window close requests, etc.
*-------------------------------------------------------------------*/
void mlx_loop_mine(t_mlx *mlx)
{
    mlx_loop(mlx->mlx_ptr);
}

void init_all_default (t_data *data)
{
    /* Set initial mlx_game*/
    data->mlx_game->mlx_ptr = NULL;
    data->mlx_game->win_ptr = NULL;
    data->mlx_game->mlx_connection = NULL;
    // data->mlx_game->pixels_ptr = NULL; //already set in my_mlx_new_image - says chatgpt
    // data->mlx_game->image_ptr = NULL; //already set in my_mlx_new_image - says chatgpt
    data->mlx_game->bpp = 0;
    data->mlx_game->endian = 0;
    data->mlx_game->line_len = 0;
    data->mlx_game->cub = data->cub;

    /* Set initial mlx_map*/
    data->mlx_map->mlx_ptr = NULL;
    data->mlx_map->win_ptr = NULL;
    data->mlx_map->mlx_connection = NULL;
    // data->mlx_map->pixels_ptr = NULL; //already set in my_mlx_new_image - says chatgpt
    // data->mlx_map->image_ptr = NULL;  //already set in my_mlx_new_image - says chatgpt
    // data->mlx_map->bpp = 0; //already set in my_mlx_new_image - says chatgpt
    data->mlx_map->endian = 0;
    // data->mlx_map->line_len = 0; //already set in my_mlx_new_image - says chatgpt
    data->mlx_map->cub = data->cub;

    /* Set initial cub*/
    //data->cub->map = NULL; //already set in read_cub_file
    // data->cub->map_height = 0; //already set in read_cub_file
    data->cub->player_position = malloc(sizeof(t_coordinates));
    data->cub->player_position->x_index = 0;
    data->cub->player_position->x_decimal = 0;
    data->cub->player_position->x_pixel = 0;
    data->cub->player_position->y_index = 0;
    data->cub->player_position->y_decimal = 0;
    data->cub->player_position->y_pixel = 0;
    data->cub->initial_player_direction_in_map = 'N';
    data->cub->player_direction_vector = malloc(sizeof(t_int_x_y));
    data->cub->player_direction_vector->x = 0;
    data->cub->player_direction_vector->y = 0;
    // data->cub->textures = malloc(sizeof(t_textures));
    // data->cub->textures->north = NULL;
    // data->cub->textures->south = NULL;
    // data->cub->textures->west = NULL;
    // data->cub->textures->east = NULL;
}

void set_player_direction_vector (t_cub *cub)
{
    if (cub->initial_player_direction_in_map == 'N')
    {
        cub->player_direction_vector->x = 0;
        cub->player_direction_vector->y = -1;
    }
    else if (cub->initial_player_direction_in_map == 'S')
    {
        cub->player_direction_vector->x = 0;
        cub->player_direction_vector->y = 1;
    }
    else if (cub->initial_player_direction_in_map == 'E')
    {
        cub->player_direction_vector->x = 1;
        cub->player_direction_vector->y = 0;
    }
    else if (cub->initial_player_direction_in_map == 'W')
    {
        cub->player_direction_vector->x = -1;
        cub->player_direction_vector->y = 0;
    }
}

void init_all(t_data *data)
{
    init_all_default(data);	
    printf(">> init_all_default was "GREEN"successfully completed\n"RESET_COLOUR);
    
    /* Player's position is set in cub->map (x_index and y_index)*/
    set_player_position(data); //cub will be updated, mlx are sent so that my_mlx_pixel_put can be used
    set_player_direction_vector(data->cub);
    printf(">> initial player_position was "BLUE"set\n"RESET_COLOUR);
    
    /*Init_window: links cub to mlx*/
    init_window(data->mlx_game, GAME, data->cub);
    init_window(data->mlx_map, MAP, data->cub);
    ft_events_init(data);

    // printf(GREEN"Post INIT_ALL:--------------------------------\n"RESET_COLOUR);
    // printf("            | mlx_game | mlx_map |\n");
    // printf("x_index     |    %d       |    %d      |\n", data->mlx_game->cub->player_position->x_index, data->mlx_map->cub->player_position->x_index);
    // printf("x_decimal   |    %.2f    |    %.2f   |\n", data->mlx_game->cub->player_position->x_decimal, data->mlx_map->cub->player_position->x_decimal);
    // printf("x_pixel     |    %d      |    %d     |\n", data->mlx_game->cub->player_position->x_pixel, data->mlx_map->cub->player_position->x_pixel);
    // printf("y_index     |    %d      |    %d     |\n", data->mlx_game->cub->player_position->y_index, data->mlx_map->cub->player_position->y_index);
    // printf("y_decimal   |   %.2f    |   %.2f   |\n", data->mlx_game->cub->player_position->y_decimal, data->mlx_map->cub->player_position->y_decimal);
    // printf("y_pixel     |    %d      |    %d     |\n", data->mlx_game->cub->player_position->x_pixel, data->mlx_map->cub->player_position->x_pixel);

    /* See results: */
    put_player_in_map(data->mlx_map); //As cub has already been linked to mlx_map in init_window, sending mlx_map as parameter should be enough
}
